services:
  # SPARK
  spark-master:
    image: custom-spark:latest
    ports:
      - "9090:8080"
      - "7077:7077"
      - "15002:15002"
      - "4040:4040"
      - "18080:18080"
    volumes:
       - ./apps:/opt/spark-apps
       - ../data:/opt/spark-data
       - ./logs:/opt/spark/logs
       - ./spark-conf:/opt/spark/conf
    environment:
      - SPARK_LOCAL_IP=spark-master
      - SPARK_WORKLOAD=master
  spark-worker-a:
    image: custom-spark:latest
    ports:
      - "9091:8080"
      - "7000:7000"
    depends_on:
      - spark-master
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=1G
      - SPARK_DRIVER_MEMORY=1G
      - SPARK_EXECUTOR_MEMORY=1G
      - SPARK_WORKLOAD=worker
      - SPARK_LOCAL_IP=spark-worker-a
    volumes:
      - ./apps:/opt/spark-apps
      - ../data:/opt/spark-data
      - ./logs:/opt/spark/logs
      - ./spark-conf:/opt/spark/conf
  spark-worker-b:
    image: custom-spark:latest
    ports:
      - "9092:8080"
      - "7001:7000"
    depends_on:
      - spark-master
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=1G
      - SPARK_DRIVER_MEMORY=1G
      - SPARK_EXECUTOR_MEMORY=1G
      - SPARK_WORKLOAD=worker
      - SPARK_LOCAL_IP=spark-worker-b
    volumes:
      - ./apps:/opt/spark-apps
      - ../data:/opt/spark-data
      - ./logs:/opt/spark/logs
      - ./spark-conf:/opt/spark/conf
  # Application
  mlflow:
    image: ghcr.io/mlflow/mlflow:latest
    ports:
      - "5000:5000"
    volumes:
        - ./apps:/opt/spark-apps
        - ../data:/opt/spark-data
        - ./frontend-apps:/opt/frontend-apps
    command: [ "mlflow","server","--host","0.0.0.0" ]

